version: '3.8'

services:
  jwt-generator:
    image: blastio/openssl
    container_name: jwt-generator
    command: >
      sh -c "[ ! -f /jwt/jwt.hex ] && openssl rand -hex 32 | tr -d '\n' > /jwt/jwt.hex || exit 0"
    volumes:
      - ./jwt:/jwt
    network_mode: none
  geth-init:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101411.4
    volumes:
      - ./world:/world
      - ./genesis.json:/genesis.json
    entrypoint: /bin/sh
    command: >
      -c "[ ! -d /world/geth ] && /usr/local/bin/geth init --datadir=/world/ /genesis.json || exit 0"
    depends_on:
      jwt-generator:
        condition: service_completed_successfully
    network_mode: none
  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101411.4
    command: >
      --datadir=/world
      --port=30301
      --http
      --http.corsdomain="*"
      --http.vhosts="*"
      --http.addr=0.0.0.0
      --http.port=8545
      --http.api=web3,debug,eth,txpool,net,engine
      --nodiscover
      --maxpeers=0
      --authrpc.port=18551
      --rollup.disabletxpoolgossip=true
      --rollup.sequencerhttp="https://worldchain-mainnet-sequencer.g.alchemy.com"
      --override.fjord=1721826000
      --override.granite=1727780400
      --override.ecotone=0
      --override.canyon=0
      --authrpc.jwtsecret="/jwt/jwt.hex"
    stop_grace_period: 360s
    depends_on:
      geth-init:
        condition: service_completed_successfully
    volumes:
      - ./jwt:/jwt
      - ./world:/world
    network_mode: host
  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.10.2
    command: >
      op-node
      --l1=""
      --l1.rpckind="any"
      --l1.beacon=""
      --l1.beacon-archiver=""
      --l2="http://127.0.0.1:18551"
      --l2.jwt-secret="/jwt/jwt.hex"
      --rollup.config="/rollup.json"
      --override.fjord=1721826000
      --override.granite=1727780400
      --override.ecotone=0
      --override.canyon=0
      --p2p.bootnodes="enode://dd4e44e87d68dd43bfc16d4fd5d9a6a2cd428986f75ddf15c8a72add0ad425852b9c36b6c5999ab7a37cc64d9bc1b68d549bc088dfa728e84dea7ae617f64e04@107.22.23.212:0?discport=30301,enode://47bd99d0bc393c6ca5569058b2d031067a3df5d05214036a5b88c9b817d52e08d7514d452b1aa623cfb3dd415136dcaf90c962e62d9337ff511fee0e9d1c8b28@18.207.96.148:0?discport=30301"
    depends_on:
      - op-geth
    volumes:
      - ./jwt:/jwt
      - ./rollup.json:/rollup.json
    network_mode: host
